"""README 生成模块"""

from datetime import datetime
from typing import List
from .config import Config
from .scraper import Paper


def generate_readme(papers: List[Paper], config: Config) -> str:
    """生成 README.md 内容"""
    lines = []

    # ---- 头部 ----
    lines.append('<div align="center">')
    lines.append("")
    lines.append("# AgentGuard 🛡️")
    lines.append("")
    lines.append("**Daily Tracking of LLM Agent Security Papers on arXiv**")
    lines.append("")
    lines.append("[![Auto Update](https://github.com/NY1024/AgentSafety-Papers/actions/workflows/daily-update.yml/badge.svg)](https://github.com/NY1024/AgentSafety-Papers/actions/workflows/daily-update.yml)")
    lines.append("[![Papers](https://img.shields.io/badge/Papers-{}-blue)](#)".format(len(papers)))
    lines.append("[![License](https://img.shields.io/badge/License-MIT-green)](#)")
    lines.append("")
    lines.append("</div>")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ---- 简介 ----
    lines.append("## 📖 简介 / Introduction")
    lines.append("")
    lines.append("自动追踪 arXiv 上大模型 Agent 安全方向的最新论文，每日更新，关键词智能分类。")
    lines.append("")
    lines.append("*Automatically tracking the latest LLM Agent security papers on arXiv, updated daily with keyword-based classification.*")
    lines.append("")
    lines.append(f"**最近更新 / Last Updated**: {datetime.now().strftime('%Y-%m-%d %H:%M')} ｜ **论文总数 / Total Papers**: {len(papers)}")
    lines.append("")

    # ---- 分类导航 ----
    lines.append("## 📑 分类导航 / Category Navigation")
    lines.append("")
    category_counts = {}
    for p in papers:
        cat = p.category or "other"
        category_counts[cat] = category_counts.get(cat, 0) + 1

    for cat_def in config.keywords.categories:
        count = category_counts.get(cat_def.name, 0)
        if count > 0:
            anchor = cat_def.name.lower()
            desc = f"{cat_def.description} / {cat_def.description_en}" if cat_def.description_en else cat_def.description
            lines.append(f"- **[{cat_def.name}](#-{anchor})** — {desc} — {count}")
    lines.append("")

    # ---- 各分类论文列表 ----
    for cat_def in config.keywords.categories:
        cat_papers = [p for p in papers if (p.category or "other") == cat_def.name]
        if not cat_papers:
            continue
        # 分类内按日期从近到远排序
        cat_papers.sort(key=lambda p: p.published, reverse=True)

        desc = f"{cat_def.description} / {cat_def.description_en}" if cat_def.description_en else cat_def.description
        lines.append(f"## 📂 {cat_def.name}")
        lines.append(f"*{desc}*")
        lines.append("")

        for p in cat_papers:
            arxiv_id = p.arxiv_id
            lines.append(f"### [{p.title}]({p.abs_url})")
            lines.append("")
            lines.append(f"- **arXiv ID**: `{arxiv_id}`")
            lines.append(f"- **作者 / Authors**: {', '.join(p.authors[:5])}{' et al.' if len(p.authors) > 5 else ''}")
            lines.append(f"- **发布日期 / Published**: {p.published}")
            if p.primary_category:
                lines.append(f"- **分类 / Category**: {p.primary_category}")
            # 可折叠的 abstract
            if p.abstract:
                lines.append("")
                lines.append("<details>")
                lines.append("<summary>📝 Abstract</summary>")
                lines.append("")
                lines.append(p.abstract)
                lines.append("")
                lines.append("</details>")
                lines.append("")
            lines.append(f"- **链接 / Links**: [Abstract]({p.abs_url}) | [PDF]({p.pdf_url})")
            if p.has_code and p.code_url:
                lines.append(f"- **代码 / Code**: [GitHub]({p.code_url})")
            lines.append("")

    # ---- 统计 ----
    if category_counts:
        lines.append("## 📊 统计 / Statistics")
        lines.append("")
        lines.append("| 分类 / Category | 论文数 / Count |")
        lines.append("|------|--------|")
        for cat_def in config.keywords.categories:
            count = category_counts.get(cat_def.name, 0)
            if count > 0:
                lines.append(f"| {cat_def.name} | {count} |")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by AgentGuard at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")

    return "\n".join(lines)
