"""README 生成模块"""

from datetime import datetime
from typing import List
from .config import Config
from .scraper import Paper


def generate_readme(papers: List[Paper], config: Config) -> str:
    """生成 README.md 内容"""
    lines = []

    # 只在 README 中展示最近 90 天的论文，完整列表在 GitHub Pages
    cutoff_date = datetime.now().strftime("%Y-%m-%d")
    from datetime import timedelta
    cutoff = (datetime.now() - timedelta(days=90)).strftime("%Y-%m-%d")
    recent_papers = [p for p in papers if p.published >= cutoff]
    archived_papers = [p for p in papers if p.published < cutoff]

    # ---- 头部 ----
    lines.append('<div align="center">')
    lines.append("")
    lines.append("# AgentGuard 🛡️")
    lines.append("")
    lines.append("**Daily Tracking of LLM Agent Security Papers on arXiv**")
    lines.append("")
    lines.append("[![Auto Update](https://github.com/NY1024/AgentSafety-Papers/actions/workflows/daily-update.yml/badge.svg)](https://github.com/NY1024/AgentSafety-Papers/actions/workflows/daily-update.yml)")
    lines.append(f"[![Papers](https://img.shields.io/badge/Papers-{len(papers)}-blue)](#)")
    lines.append("[![License](https://img.shields.io/badge/License-MIT-green)](#)")
    lines.append("")
    lines.append("</div>")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ---- 简介 ----
    lines.append("## 📖 简介 / Introduction")
    lines.append("")
    lines.append("自动追踪 arXiv 上大模型 Agent 安全方向的最新论文，每日更新，关键词智能分类。")
    lines.append("")
    lines.append("*Automatically tracking the latest LLM Agent security papers on arXiv, updated daily with keyword-based classification.*")
    lines.append("")
    lines.append(f"**最近更新 / Last Updated**: {datetime.now().strftime('%Y-%m-%d %H:%M')} ｜ **论文总数 / Total Papers**: {len(papers)}（近 90 天 / Recent 90 days: {len(recent_papers)}）")
    lines.append("")
    lines.append("🌐 **[GitHub Pages](https://ny1024.github.io/AgentSafety-Papers/)** — 完整论文列表（含摘要可折叠展示）/ Full paper list with collapsible abstracts")
    lines.append("")

    # ---- 分类导航 ----
    lines.append("## 📑 分类导航 / Category Navigation")
    lines.append("")
    category_counts = {}
    for p in papers:
        cat = p.category or "other"
        category_counts[cat] = category_counts.get(cat, 0) + 1

    for cat_def in config.keywords.categories:
        count = category_counts.get(cat_def.name, 0)
        if count > 0:
            anchor = cat_def.name.lower()
            desc = f"{cat_def.description} / {cat_def.description_en}" if cat_def.description_en else cat_def.description
            lines.append(f"- **[{cat_def.name}](#-{anchor})** — {desc} — {count}")
    lines.append("")

    # ---- 各分类论文列表（仅近90天，紧凑单行格式） ----
    lines.append(f"## 📄 近期论文 / Recent Papers (Last 90 Days)")
    lines.append("")
    lines.append(f"> 完整论文列表（含 {len(archived_papers)} 篇历史论文）请访问 [GitHub Pages](https://ny1024.github.io/AgentSafety-Papers/)")
    lines.append("")
    lines.append(f"> Full archive ({len(archived_papers)} historical papers) available on [GitHub Pages](https://ny1024.github.io/AgentSafety-Papers/)")
    lines.append("")

    for cat_def in config.keywords.categories:
        cat_papers = [p for p in recent_papers if (p.category or "other") == cat_def.name]
        if not cat_papers:
            continue
        cat_papers.sort(key=lambda p: p.published, reverse=True)

        desc = f"{cat_def.description} / {cat_def.description_en}" if cat_def.description_en else cat_def.description
        lines.append(f"### 📂 {cat_def.name}")
        lines.append(f"*{desc}* — {len(cat_papers)} papers")
        lines.append("")

        for p in cat_papers:
            title = p.title.strip()
            lines.append(f"- **{p.published}** [{title}]({p.abs_url})")

        lines.append("")

    # ---- 统计 ----
    if category_counts:
        lines.append("## 📊 统计 / Statistics")
        lines.append("")
        lines.append("| 分类 / Category | 论文数 / Count |")
        lines.append("|------|--------|")
        for cat_def in config.keywords.categories:
            count = category_counts.get(cat_def.name, 0)
            if count > 0:
                lines.append(f"| {cat_def.name} | {count} |")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by AgentGuard at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")

    return "\n".join(lines)
